name: The Gut Feeling
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73728
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1feff'
    - '#0e7f87'
    - '#9dbab9'
    - '#0ba3a3'
    - '#7c9da9'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
