name: The Gut Feeling
favicon: null
layout_spectrum: 0.75616
typography_spectrum: 0.01070823683403432
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8953466690145433
  lightness: 0.6015037
  saturation: 0.89599
  rhythmicContrast: 0.7800752
purpose: []
